# -*- coding: utf-8 -*-
"""
Created on Thu Apr 27 10:03:01 2017

@author: Niranjan
"""
# This program plot the absorption spectrum from the EXC.DAT file
# generated by the DFTB+ program. With small modifications, in the
# way data is read, this can be generalized for any other program
# output as well. The program needs excitation energies and 
# corresponding oscillator strengths.

import numpy as np
import matplotlib.pyplot as plt

#CONSTANTS
hc = 1240 #eV.nm #conversion factor for eV <-> nm

#PEAK BROADENING VALUE
sigma = 0.2 #eV

#IMPORT DATA FROM EXC.DAT FILE GENERATED BY DFTB+(Version 1.3 and onwards)
#Use line below for DFTB
data = np.genfromtxt('EXC.DAT',skip_header=4,usecols=np.arange(0,8))

#Tips about skip_header
# -- Check the EXC.DAT file. Sometimes the initial 2-3 energies are listed as 0.00 eV. 
# -- You will have to delete all these lines by changing the skip_header number
# -- Or the program will give an error

#EXTRACTING ENERGY AND OSCILLATOR STRENGTH VALUES
eV = data[:,0]
osci = data[:,1]

#CONVERT FROM ENERGY (eV) to WAVELENGTH (nm)
wav = hc/eV

#CONVERT SIGMA FROM EV TO NM
sigma_nm = hc/sigma #nm

#ADJUST THIS ACCORDING TO THE WAVELENGTH RANGE ONE IS INTERESTED IN
lam = np.arange(100,1400,1)

E=np.empty(len(lam))

#HEART OF THE PROGRAM
#TO GET DETAILS VISIT BEHIND THE MATHS, VISIT http://gaussian.com/uvvisplot/
for i in range(len(wav)):
    E=E+1.3062974*10**8*osci[i]/10**7*sigma_nm*np.exp(-(((1/lam)-(1/wav[i]))/(1/sigma_nm))**2)

#TO PLOT ABSORPTION SPECTRUM IN TERMS OF WAVELENGTH, UNCOMMENT FOLLOWING LINE

#PLOTTING ABSORPTION SPECTRUM IN EV
lam_eV = hc/lam
plt.plot(lam_eV,E)

#SAVING RESULTS TO A TEXT FILE
DataOut = np.column_stack((lam_eV,E))
np.savetxt("ABS_SPECTRUM.DAT",DataOut)
